image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.3"
  ANDROID_SDK_TOOLS: "4333796"

before_script:
  - wget --quiet --output-document=/tmp/sdk-tools-linux.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip /tmp/sdk-tools-linux.zip -d .android
  - export ANDROID_HOME=$PWD/.android
  - export PATH=$PATH:$PWD/.android/platform-tools/
  - echo y | .android/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - curl -sL https://deb.nodesource.com/setup_12.x | bash
  - apt-get install -y nodejs
  - npm install -g react-native-cli
  - npm install
  - chmod +x android/gradlew
 
stages:
  - test

test:
  stage: test
  script:
    - npm test