// https://hub.docker.com/r/reactnativecommunity/react-native-android/
image: reactnativecommunity/react-native-android

before-scripts:
  - npm install -g envinfo && envinfo

stages:
  - test
  - build-android

test:
  stage: test
  script:
    - npm test

build-android:
  stage: build-android
  script:
    - npm install
    - cd android && chmod +x gradlew
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - android/app/build/outputs/